# Form implementation generated from reading ui file 'steamTrace.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_steamTrace(object):
    def setupUi(self, steamTrace):
        steamTrace.setObjectName("steamTrace")
        steamTrace.resize(1200, 800)
        self.widget = QtWidgets.QWidget(parent=steamTrace)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1190, 800))
        self.widget.setObjectName("widget")

        self.retranslateUi(steamTrace)
        QtCore.QMetaObject.connectSlotsByName(steamTrace)

    def retranslateUi(self, steamTrace):
        _translate = QtCore.QCoreApplication.translate
        steamTrace.setWindowTitle(_translate("steamTrace", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    steamTrace = QtWidgets.QWidget()
    ui = Ui_steamTrace()
    ui.setupUi(steamTrace)
    steamTrace.show()
    sys.exit(app.exec())
